var draggables = document.getElementsByClassName("word ui-draggable")
undefined
draggables
HTMLCollection(42) [span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle]
draggables = Array.prototype.slice.call(draggables);
(42) [span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle, span.word.ui-draggable.ui-draggable-handle]
draggables.forEach(select)
VM23078:2 Uncaught TypeError: element.addClass is not a function
    at select (<anonymous>:2:13)
    at Array.forEach (<anonymous>)
    at <anonymous>:1:12
select @ VM23078:2
(anonymous) @ VM25402:1
function select(element) {
    element.classList.add('selected');
}
